/// generation start ////////////////////////////////////////////////////////////

///
/// main.cpp automatically generated by TUG Wizard at 2016-01-21 14:03:01.841
///

#include <QApplication>
#include <TestBinRunner.h>


/// main function
int main(int argc, char *argv[])
{
    ///
    /// 1. create a test runner and configure...

    TestBinRunner trunner(argc,argv);
    trunner.project_name("MainWindowTestproject");

    // output options
    trunner.output_verbose();
    //trunner.add_timestamp_to_output_filename();

    // coverage and profiling options

    ///
    /// 2. add test binaries to the runner

    trunner.add_testbin("Testsuite_MainWindow_1",
        "./Testsuite_MainWindow_1",
        "&amp;lt&#59;No description set for this Testsuite&amp;gt&#59;");
    trunner.add_testbin("Testsuite_Mainwindow_2",
        "./Testsuite_Mainwindow_2",
        "");
    trunner.add_testbin("Testsuite_base_MainWindow",
        "./Testsuite_base_MainWindow",
        "");

    ///
    /// 3. run tests

    return trunner.pause_between(1000).run();
}

/// generation end ////////////////////////////////////////////////////////////
