#/// generation start ////////////////////////////////////////////////////////////

#-------------------------------------------------------------------------------
# Qt project automatically generated by TUG Wizard at 2016-01-21 14:03:01.841
#-------------------------------------------------------------------------------

# target
PROJECT_NAME = MainWindowTestproject
TARGET = do_test_MainWindow
TEMPLATE = app
BUILD_DIR = ../../bin
DESTDIR = $${BUILD_DIR}

# config
QT += core gui testlib
CONFIG += debug


equals(QT_MAJOR_VERSION, 5) {
  message(" Using QT 5 kit...")
   QT += widgets
}
else {
  message(" Using QT 4 kit...")
}

#-------------------------------------------------------------------------------

###
### main sources
SOURCES += main.cpp
SOURCES += test_MainWindow.cpp
HEADERS += test_MainWindow.h


#-------------------------------------------------------------------------------

###
### panel sources
INCLUDEPATH += ../../../../panel_to_test/

###
### gw sources
INCLUDEPATH += ../../../../panel_to_test/
# extra includes
# SOURCES += 
# HEADERS += 
# DEPENDPATH += 
# INCLUDEPATH += 
# LIBS +=

SOURCES += ../../../../panel_to_test/mainwindow.cpp
FORMS += ../../../../panel_to_test/mainwindow.ui
HEADERS += ../../../../panel_to_test/mainwindow.h



# signal includes (configured in file)
# no signals selected

#-------------------------------------------------------------------------------

# TUG lib include (configured in file)
TUG_LIB_PATH = /tmp/libtug/lib/
TUG_INCLUDE_PATH = /tmp/libtug/include/
DEPENDPATH += $${TUG_LIB_PATH}
INCLUDEPATH += $${TUG_INCLUDE_PATH}
LIBS += -L$${TUG_LIB_PATH} -lTUG


# gcov includes (configured in file)
# gcov not selected

# gprof includes (configured in file)
# gprof not selected

# qwt includes (configured in file)
# qwt not selected

# extra includes (configured in wizard)
# SOURCES += 
# HEADERS += 
# DEPENDPATH += 
# INCLUDEPATH += 
# LIBS +=

#/// generation end ////////////////////////////////////////////////////////////
