/// generation start ////////////////////////////////////////////////////////////

///
/// test_MainWindow.h automatically generated by TUG Wizard at 2016-01-21 14:03:01.856
///

#ifndef TEST_MainWindow_H
#define TEST_MainWindow_H

// ui include
#include <ui_mainwindow.h>

// gw include
#include <mainwindow.h>

///
/// additional includes (protected area)

/// >>>>>

/// <<<<<

///
/// test_MainWindow class definition
///

class test_MainWindow 
    : public MainWindow 
{

    friend class Testsuite_MainWindow_1;
    friend class Testsuite_Mainwindow_2;
    friend class Testsuite_base_MainWindow;

public:

    ///
    /// constructors

    test_MainWindow();
    test_MainWindow(QWidget* parent);
    ~test_MainWindow();

protected:

	///
	/// supporting code (protected area)
	
	/// >>>>>

    /// <<<<<

public:

    ///
    /// widget methods

   
   
      // label
      void set_label(const std::string& s);
      const std::string get_label();
   
      QLabel* acc_label();
   
   
      // label_3
      void set_label_3(const std::string& s);
      const std::string get_label_3();
   
      QLabel* acc_label_3();
   
   
      // le_password
      void set_le_password(const std::string& s);
      const std::string get_le_password();
   
      QLineEdit* acc_le_password();
   
   
      // le_username
      void set_le_username(const std::string& s);
      const std::string get_le_username();
   
      QLineEdit* acc_le_username();
   
   
      // pb_login
      void doClick_pb_login();
   
      QPushButton* acc_pb_login();
   
   
      // lbl_status
      void set_lbl_status(const std::string& s);
      const std::string get_lbl_status();
   
      QLabel* acc_lbl_status();
   
   
   
   
   
   
};

#endif // TEST_MainWindow_H

/// generation end ////////////////////////////////////////////////////////////
