
# ------------------------------------------------
* Paso 2: Crear una nueva TestSuite para un panel

** ¿Qué necesitamos?

Para crear una nueva testsuite definiremos una nueva clase que
heredará de la superclase ~TestSuiteBase~. La librería en la que
podemos encontrar esta clase base junto con el resto de utilidades que
mencionaremos en esta sección tiene el nombre de
~libcasa_gui_testing.so.1.0.0~, y se puede encontrar en la carpeta
~tug_lib/~.

A la hora de definir la nueva testsuite utilizaremos, aparte de la
clase base, una serie de macros y métodos de apoyo a los que podremos
acceder incluyendo el fichero ~#include <TestSuiteBase.h>~ en nuestra
testsuite.


** Descripción de la clase TestSuiteBase

La clase ~TestSuiteBase~ será la base de cualquier testsuite que
definamos con la librería TUG. 

Para definir un nuevo conjunto de tests sólo necesitamos crear una
nueva clase que herede de ~TestSuiteBase~, la cual puede ser
referenciada incluyendo el siguiente fichero: ~#include
<TestSuiteBase.h>~

*** Métodos de TestSuiteBase que pueden ser sobrecargados


Algunos métodos de la clase ~TestSuiteBase~ pueden ser opcionalmente
redefinidos con el objetivo de añadir nuestra propia funcionalidad
para inicialización (antes) y limpieza (después) tanto de la testsuite
como de cada uno de los tests.  Éstos son los siguientes:

+ ~virtual void configure_testsuite()~: Método de configuración que se
  llama al inicio de una test suite.

+ ~virtual void finish_testsuite()~ : Método de finalización que se
  llama al final de una test suite.

+ ~virtual void configure_test()~ : Método de configuración que se
  llama al inicio de cada uno de los tests.

+ ~virtual void finish_test()~ : Método de finalización que se llama al
  final de cada uno de los tests.

+ ~virtual void do_tests()~ : Método que ejecuta todos los tests
  incluídos en la testsuite.


~TestSuiteBase~ también proporciona un método ~static~ que nos permite
ejecutar una testsuite desde cualquier parte del código fuente de la
aplicación:

+ ~static int launch(TestSuiteBase* tsb,int argc=0,char *argv[]=0);~

+ ~static int launch(TestSuiteBase& tsb,int argc=0,char *argv[]=0);~

Como se puede comprobar en estos métodos, una testsuite puede lanzarse
(opcionalmente) incluyendo los argumentos de programa.


** Descripción de las macros y utilidades de test

Las macros nos facilitan las tareas más comunes dentro de un test. A
la hora de definir un nuevo test utilizaremos estas macros para, por
ejemplo, lanzar un panel, repintarlo, realizar una espera para
obtener un resultado, crear rangos de valores, etc.


# *** Ejecución de la testsuite
# 
# La ejecución de la testsuite se lanzará usando la siguiente macro. Una
# vez se llame a ~t_TESTSUITE_EXEC()~ todos los tests serán ejecutados
# como una batería, y el resultado de la ejecución se mostrará al final
# de la misma.
# 
# #+NAME: asdfre
# #+BEGIN_SRC cpp
# ________________________________________________________________
# // (mandatory) This macro executes all the tests declared in
# // this test suite. In addition, initTestCase(),
# // cleanupTestCase(), init() and cleanup() are executed if they
# // exist.
# #define t_TESTSUITE_EXEC()
# ________________________________________________________________
# #+END_SRC


*** Lanzamiento y repintado de paneles:

Recomendamos que los paneles se lancen con alguna de estas dos
macros: 
+ ~t_LAUNCH_PANEL(type, panel_name)~ crea un objeto panel del tipo
  /type/ y con nombre /panel_name/ que no necesita ser eliminado al
  final del test.

+ ~t_SHOW_PANEL(panel_pointer)~ mostrará el panel /panel_pointer/, el
  cual deberá ser eliminado al final del test.

En el caso de que queramos controlar completamente la forma en que se
crea y se lanza un panel, éstos también pueden ser lanzados y
eliminados de forma manual.

Por otra parte, la macro ~t_REPAINT(panel)~ nos permite refrescar el
panel en el caso de que queramos ver los cambios realizados en la GUI
en tiempo real. Por defecto Qt 4.8 cuenta con un sistema de optimizado
a la hora de renderizar el panel, el cual no muestra los cambios
realizados a la interfaz mediante otros métodos que no sea la
interacción desde ratón o teclado.

Las macros ~t_BLINK_PANEL(panel)~ y
~t_BLINK_PANEL_POINTER(panel_pointer)~ nos permiten ocultar y mostrar
el panel con el fin de crear un efecto parpadeo. Esto puede ser muy
útil, por ejemplo, para mostrar que un nuevo test acaba de empezar.

#+NAME: asdfre
#+BEGIN_SRC cpp
________________________________________________________________
// (optional) This macro helps you to create and deploy a new
// panel. As alternative, you can create a panel and launch it
// manually. Remember that the panel you created has to be
// hidden and destroyed properly.
#define t_LAUNCH_PANEL(type, panel_name)
#define t_SHOW_PANEL(panel_pointer) 

// (optional) This macro forces a panel repaint for developers
// to notice the changes done by code.
#define t_REPAINT(panel)

// (optional) This macro hides and show the panel in order to create
// a blink effect
#define t_BLINK_PANEL(panel) 

// (optional) This macro hides and show the panel in order to create
// a blink effect
#define t_BLINK_PANEL(panel_pointer) 
________________________________________________________________
#+END_SRC

*** Control y simulación de tiempos en el test:

Este conjunto de macros nos permiten simular una espera entre las
diferentes acciones que se realizan en un test. Son especialmente
útiles en el caso que queramos simular la acción del usuario o que
necesitemos esperar para la producción de un resultado.

#+NAME: asdfre
#+BEGIN_SRC cpp
________________________________________________________________
// (optional) This macro sleeps 'ms' milliseconds
#define t_SLEEP(ms)

// (optional) This macro sleeps 1000 milliseconds
#define t_SLEEP_1()

// (optional) This macro sleeps 2000 milliseconds
#define t_SLEEP_2()

// (optional) This macro sleeps 3000 milliseconds
#define t_SLEEP_3()

// (optional) This macro sleeps 5000 milliseconds
#define t_SLEEP_5()

// (optional) This macro executes 'action' after 'ms'
// milliseconds
#define t_DELAYED(action,ms)
________________________________________________________________
#+END_SRC




*** Valores aleatorios:

Este conjunto de macros nos permiten generar valores aleatorios de
diferentes tipos. La macro ~t_RESET_RANDOM()~ nos permite reiniciar
la semilla que se utiliza para generar estos valores.

#+NAME: asdfre
#+BEGIN_SRC cpp
________________________________________________________________
// (optional) This macro resets the seed used for the value generation
#define t_RESET_RANDOM() 

// (optional) This macro returns a random number smaller than n
#define t_RANDOM(n) 

// (optional) This macro returns a random number between 'low' and
// 'high', both included
#define t_RANDOM_RANGE(low,high) 

// (optional) This macro returns a random boolean
#define t_RANDOM_BOOL() 
________________________________________________________________
#+END_SRC



*** Rangos de valores:

Este conjunto de macros nos permite generar un rango de valores entre
~min~ y ~max~ utilizando ~inc~ como incremento. Los valores generados
se pueden utilizar con el nombre de variable que pasemos en el campo
~val~.

#+NAME: asdfre
#+BEGIN_SRC cpp
________________________________________________________________
// (optional) This macro simulates an integer range between 'min'
// and 'max', both included. 'val' is the name of the generated value.
#define t_INT_RANGE(val,min,max)

// (optional) This macro simulates an integer range between 'min'
// and 'max', both included, using 'inc' as increment. 
// 'val' is the name of the generated value.
#define t_INT_RANGE_INC(val,min,max,inc)

// (optional) This macro simulates a float range between 'min' and
// 'max', both included, using 'inc' as increment.  
// 'val' is the name of the generated value.
#define t_FLOAT_RANGE(val,min,max,inc)
________________________________________________________________
#+END_SRC



*** Aserciones y comprobaciones:

Este conjunto de macros nos permite llevar a cabo diferentes tipos de
aserciones y comprobaciones. El resultado de las mismas será mostrado
por pantalla, y quedará reflejado en el resumen final de la ejecución
de la batería de tests.

#+NAME: asdfre
#+BEGIN_SRC cpp
________________________________________________________________
// t_COMPARE(actual,expected)
// This macro compares an actual value to an expected value
// using the equals operator. If actual and expected are
// identical, execution continues. If not, a failure is recorded
// in the test log and the test won't be executed further.
#define t_COMPARE(actual,expected)

// t_ASSERT(condition)
// The QVERIFY() macro checks whether the condition is true or
// not. If it is true, execution continues. If not, a failure is
// recorded in the test log and the test won't be executed
// further.
#define t_ASSERT(condition)

// t_ASSERT_MSG(condition,msg)
// This macro behaves exactly like t_ASSERT(condition), except
// that it outputs a verbose message when condition is false.
// The message is a plain C string.
#define t_ASSERT_MSG(condition,msg) 

// t_FAIL(msg)
// This macro can be used to force a test failure. The test 
// stops executing and the failure message is appended to the 
// test log.
#define t_FAIL(msg)
________________________________________________________________
#+END_SRC

*** Utilidades de advertencia y log:

Estas macros nos permiten mostrar por la salida estándard mensajes de
log (irán etiquetados con /QDEBUG/) y mensajes de advertencia (irán
etiquetados con /WARNING/.)

#+NAME: asdfre
#+BEGIN_SRC cpp
________________________________________________________________
// t_WARN(msg)
// Appends message as a warning to the test log. This macro can
// be used anywhere in your tests.
#define t_WARN(msg)

// t_LOG(msg)
// Displays 'msg' in the standard output.
#define t_LOG(text)
________________________________________________________________
#+End_SRC



** Definición de una testsuite (Ejemplo práctico)

En esta sección crearemos un ejemplo completo de una testsuite para el
panel /PanelXXX/, para el cual previamente habremos generado su
correspondiente clase de test /test\_PanelXXX/. El ejemplo incluye
una serie de métodos de configuración, así como la definición de 3
tests para el panel previamente mencionado.

+ *Paso 1: Includes*\\ Para definir una nueva testsuite tendremos que incluir,
   como mínimo, la clase correspondiente al panel a testear y el
   fichero ~<TestSuiteBase.h>~.

#+BEGIN_SRC cpp
________________________________________________________________
#ifndef TESTSUITE_PANELXXX_HPP
#define TESTSUITE_PANELXXX_HPP

#include "test_PanelXXX.h"

///
/// Our test suite has to extend the TestSuiteBase class in order to inherit all
/// the functionality needed to define and execute the tests.

#include <TestSuiteBase.h>
________________________________________________________________
#+END_SRC

+ *Paso 2: Crear la clase testsuite*\\ La testsuite que definamos
  deberá heredar de la clase ~TestSuiteBase~. Además, será
  obligatorio incluir la macro ~Q_OBJECT~ para permitir la ejecución
  automática de los tests.

#+BEGIN_SRC cpp
________________________________________________________________
class testsuite_PanelXXX : public TestSuiteBase {

    Q_OBJECT /// (mandatory) Our test suite has to execute Q_OBJECT macros

public:

    /// /////////////////////////////////////////////////////
    ///
    /// TestSuite constructor (optional)
    ///

    testsuite_PanelXXX()
    {}
________________________________________________________________
#+END_SRC

+ *Paso 3: Redefinición de los métodos de inicialización y limpieza de
  la clase base TestSuiteBase (opcional)*\\ La clase base de la
  testsuite proporciona 4 métodos que pueden ser redefinidos en caso
  de que queramos definir un comportamiento adicional al inicio y fin
  de la ejecución tanto de la testsuite como de los tests
  individualmente. \\ Estos métodos son ~configure_testsuite()~ (se
  ejecuta antes de la ejecución de la testsuite), ~finish_testsuite()~
  (se llama justo cuando la ejecución de todos los tests ha
  finalizado), ~configure_test()~ (se ejecuta antes de la ejecución de
  cada test) y ~finish_test()~ (se llama justo después de la ejecución
  de cada test).  Por otra parte, la macro ~do_tests()~ permite
  definir comportamiento extra antes y/o después de ejecutar la
  batería de tests. \\ Estos métodos SE CONSIDERAN COMO TESTS en la
  testsuite, por lo que en el caso de que exista algún error durante
  la ejecución de ellos, estos errores quedarán reflejados en el
  resumen final de la ejecución.



#+BEGIN_SRC cpp
________________________________________________________________
    /// /////////////////////////////////////////////////////
    ///
    /// TestSuiteBase overloaded methods (optional)
    ///

public:

    ///
    /// (optional) this method can be redefined if additional configurations
    /// have to be performed before test suite execution
    virtual void configure_testsuite()
    {
        //your initialization code here
    }

    ///
    /// (optional) this method can be redefined if additional actions have to
    /// be executed before finishing the test suite

    virtual void finish_testsuite()
    {
        //your finalization code here

        TestSuiteBase::finish_testsuite(); //mandatory
    }
________________________________________________________________
#+END_SRC



+ *Paso 4: Definición de los tests*\\ Los tests se definen como
  métodos estándar. Sin embargo, para permitir la ejecución automática
  éstos deben definirse como ~private Q_SLOTS~ como se muestra en el
  código a continuación.

#+BEGIN_SRC cpp
________________________________________________________________
    /// /////////////////////////////////////////////////////
    ///
    /// Tests definition
    ///

private Q_SLOTS: /// (mandatory) Tests have to be declared as "private slots"
________________________________________________________________
#+END_SRC

+ *Paso 5: Comenzar la definición de un test. Lanzamos el
  panel.*\\ Creamos un nuevo método con nombre /test\_1()/ para definir
  el primer test de la testsuite. Para lanzar el panel utilizaremos en
  este caso la macro ~t_LAUNCH_PANEL(test_PanelXXX,panel);~, la cual
  nos creará un objeto del tipo ~test_PanelXXX~ con nombre /panel/.

#+BEGIN_SRC cpp
________________________________________________________________
    void test_1()
    {
        ///
        /// launch test

        // Alternative 1: use t_LAUNCH_PANEL macro
        //  - test_PanelXXX -> class to be launched
        //  - panel -> name of the panel created
        t_LAUNCH_PANEL(test_PanelXXX,panel);

        ///
        /// test implementation
        t_LOG("_____ This is 'test 1'");
________________________________________________________________
#+END_SRC

+ *Paso 6: Establecemos valores en el panel*\\ Para establecer valores
  en el panel utilizaremos la API de test que habremos generado
  previamente. Llamaremos a la macro ~t_REPAINT(panel);~ para que los
  cambios se puedan apreciar antes de la pausa introducida a
  continuación.

#+BEGIN_SRC cpp
________________________________________________________________
        // set some values in the panel
        panel.set_sbLatDegrees(60);// 0-90
        panel.set_sbLatMin(59);
        panel.set_sbLongDegrees(36);// 0-180
        panel.set_sbLongMin(33);
        t_REPAINT(panel);
        t_SLEEP_1();
________________________________________________________________
#+END_SRC

+ *Paso 7: Realizamos comprobaciones en el panel*\\ Para realizar las
  comprobaciones utilizaremos las macros destinadas a dicho
  propósito. El test finalizará en cuanto se encuentre el primer
  fallo, y será anotado como /FAILED/. En caso de que no haya ningún
  error durante las comprobaciones, el test será anotado como
  /PASSED/.

#+BEGIN_SRC cpp
________________________________________________________________
        // check something
        t_ASSERT(panel.get_sbLatDegrees() >=0 &&
                 panel.get_sbLatDegrees() <=90);
        t_ASSERT_MSG(panel.get_sbLongDegrees() >=0 &&
                 panel.get_sbLongDegrees() <=90,
                     "Longitude Degrees KO"); //message not displayed
                                              //because no error
        t_WARN("An error was introduced next...");
        t_COMPARE(panel.get_sbLatDegrees(),
                  panel.get_sbLongDegrees()); //test fails and stops here...
        t_SLEEP_3();
    }
________________________________________________________________
#+END_SRC

+ *Paso 8: Definimos un segundo test*\\ En este punto definimos un
  nuevo test donde las principales diferencias con el test anterior
  son las siguientes:
  - Lanzamos el panel como un puntero usando la macro ~t_SHOW_PANEL~
  - Realizamos acciones de click sobre botones
  - Intercalamos modificaciones del panel con comprobaciones
    intermedias
  - Simulamos un error con la macro ~t_FAIL~
  - Eliminamos el panel, ya que se trata de un puntero

#+BEGIN_SRC cpp
________________________________________________________________
    void test_2(){

        ///
        /// launch test

        // Alternative 2: create the panel ourselves and use t_SHOW_PANEL to
        // show the panel window.
        //  - test_PanelXXX -> panel class
        //  - panel -> object to be tested
        test_PanelXXX* panel = new test_PanelXXX();
        t_SHOW_PANEL(panel);

        ///
        /// test implementation
        t_LOG("_____ This is 'test 2'");

        // set some values in the panel
        panel->set_sbLatDegrees(10);panel->set_sbLatMin(10);
        panel->set_sbLongDegrees(10);panel->set_sbLongMin(10);
        t_REPAINT(panel);
        t_SLEEP_1();

        // simulate some behavior
        panel->doClick_btApplyCenter();t_SLEEP_1();
        panel->set_cbBuoyCenter(1);t_SLEEP_1();

        // check if centered
        t_COMPARE(panel->get_pbarState(),1);

        // simulate some behavior
        panel->doClick_btCenterOnCarrier();t_SLEEP_1();

        // check if on carrier
        t_COMPARE(panel->get_pbarState(),2);

        // ending
        t_LOG("All tests were ok...");
        t_WARN("...however, we can also simulate test fails");
        t_FAIL("This is a forced error!");
        t_SLEEP_3();

        ///
        /// delete panel -- mandatory for pointers
        delete panel;
    }
________________________________________________________________
#+END_SRC

+ *Paso 9: Definimos un tercer test*\\ En este punto definimos un
  nuevo test donde la principal diferencia con los tests
  anteriores es que no contiene ningún error, por lo que será anotado
  como /PASSED/.

#+BEGIN_SRC cpp
________________________________________________________________
    void test_3()
    {
        ///
        /// launch test
        t_LAUNCH_PANEL(test_PanelXXX,panel);

        ///
        /// test implementation
        t_LOG("_____ This is 'test 3'");

        // set some values in the panel
        panel.set_sbLatDegrees(60);panel.set_sbLatMin(59);
        panel.set_sbLongDegrees(36);panel.set_sbLongMin(33);
        t_REPAINT(panel);
        t_SLEEP_1();

        // check something
        t_ASSERT(panel.get_sbLatDegrees() >=0 &&
                 panel.get_sbLatDegrees() <=90);
        t_ASSERT_MSG(panel.get_sbLongDegrees() >=0 &&
                 panel.get_sbLongDegrees() <=90,
                     "Longitude Degrees KO"); //message not displayed 
                                              //because no error
        t_WARN("This test has no errors.");
        t_SLEEP_3();
    }

};

#endif // TESTSUITE_PANELXXX_HPP
________________________________________________________________
#+END_SRC




