#/// generation start ////////////////////////////////////////////////////////////

#-------------------------------------------------------------------------------
# Qt project automatically generated by TUG Wizard at 2016-01-21 14:03:01.818
#-------------------------------------------------------------------------------

# main target
PROJECT_NAME = MainWindowTestproject
TEMPLATE = subdirs
BUILD_DIR = bin
DESTDIR = $${BUILD_DIR}
MOC_DIR = $${BUILD_DIR}/mocs
OBJECTS_DIR = $${BUILD_DIR}/objs

# config
QT       += core gui testlib
CONFIG += no_keywords debug

equals(QT_MAJOR_VERSION, 5) {
  message(" Using QT 5 kit...")
   QT += widgets
}
else {
  message(" Using QT 4 kit...")
}



# testsuite targets
SUBDIRS += tests/_testpanel/MainWindow_testproject.pro
SUBDIRS += tests/Testsuite_MainWindow_1
SUBDIRS += tests/Testsuite_Mainwindow_2
SUBDIRS += tests/Testsuite_base_MainWindow


#/// generation end ////////////////////////////////////////////////////////////
