#/// generation start ////////////////////////////////////////////////////////////

#---------------------------------------------------------------------------------
# Qt project automatically generated by TUG Wizard at (TODO add timestamp here)
#---------------------------------------------------------------------------------

# target
TARGET = Testsuite_Mainwindow_2
TEMPLATE = app
BUILD_DIR = ../../bin
DESTDIR = $${BUILD_DIR}

# config
QT += core gui testlib
CONFIG += debug

equals(QT_MAJOR_VERSION, 5) {
  message(" Using QT 5 kit...")
   QT += widgets
}
else {
  message(" Using QT 4 kit...")
}

MAINTEST_PATH = ../_testpanel/
DEPENDPATH += $${MAINTEST_PATH}
INCLUDEPATH += $${MAINTEST_PATH}


#---------------------------------------------------------------------------------

###
### main sources
SOURCES += Testsuite_Mainwindow_2_main.cpp
SOURCES += $${MAINTEST_PATH}/test_MainWindow.cpp

###
### test includes
HEADERS  += ../Testsuite_base_MainWindow.hpp ../
HEADERS  += ../Testsuite_Mainwindow_2.hpp
HEADERS  += $${MAINTEST_PATH}/test_MainWindow.h

#---------------------------------------------------------------------------------

###
### panel and gw sources
PANEL_LIB_PATH = 
PANEL_INC_PATH = ../../../../panel_to_test/
DEPENDPATH += $${PANEL_LIB_PATH}
INCLUDEPATH += $${PANEL_LIB_PATH}/../include/ # try our luck
INCLUDEPATH += $${PANEL_INC_PATH}
LIBS += -L$${PANEL_LIB_PATH} -l
# extra includes
# SOURCES += 
# HEADERS += 
# DEPENDPATH += 
# INCLUDEPATH += 
# LIBS +=

SOURCES += ../../../../panel_to_test/mainwindow.cpp
FORMS += ../../../../panel_to_test/mainwindow.ui
HEADERS += ../../../../panel_to_test/mainwindow.h


###
### model sources
MODEL_LIB_PATH = ../
MODEL_INC_PATH = ../
DEPENDPATH += $${MODEL_LIB_PATH}
INCLUDEPATH += $${MODEL_LIB_PATH}/../include/ # try our luck
INCLUDEPATH += $${MODEL_INC_PATH}
LIBS += -L$${MODEL_LIB_PATH} 
# extra includes



###
### signals sources
CONFIG += 
SIGNALS_LIB_PATH = ../
SIGNALS_INC_PATH = ../
DEPENDPATH += $${SIGNALS_LIB_PATH}
INCLUDEPATH += $${SIGNALS_LIB_PATH}/../include/ # try our luck
INCLUDEPATH += $${SIGNALS_INC_PATH}
LIBS += -L$${SIGNALS_LIB_PATH} 
# extra includes



# signal includes (configured in file)
# add in the configuration file the lines to include boost signals


#---------------------------------------------------------------------------------

# NOTE: all library directories depend on building directory

# TUG lib include (configured in file)
TUG_LIB_PATH = /tmp/libtug/lib/
TUG_INCLUDE_PATH = /tmp/libtug/include/
DEPENDPATH += $${TUG_LIB_PATH}
INCLUDEPATH += $${TUG_INCLUDE_PATH}
LIBS += -L$${TUG_LIB_PATH} -lTUG



# gcov includes (configured in file)
# add in the configuration file the lines to include gcov
# gcov not selected


# gprof includes (configured in file)
# add in the configuration file the lines to include gprof
# gprof not selected


# qwt includes (configured in file)
# add in the configuration file the lines to include qwt
# qwt not selected


# extra includes (configured in wizard)
# SOURCES += 
# HEADERS += 
# DEPENDPATH += 
# INCLUDEPATH += 
# LIBS +=


#/// generation end ////////////////////////////////////////////////////////////

